name: TM - SAP Build Code Setup

on:
  #  push:
  #    branches:
  #      - main
  workflow_dispatch:

env:
  PATH_TO_TFSCRIPT: "infra-terramate"

jobs:
  execute_base_setuup:
    name: BTP Sample Setup (Terramate)
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        id: checkout_repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        id: setup_terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: latest

      - name: Setup Terramate
        id: setup_terramate
        uses: terramate-io/terramate-action@v2
        with:
          use_wrapper: "false"
          version: latest

      - name: Initialize Terraform
        id: terraform_init
        shell: bash
        run: |
          export export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
          terramate run --tags dev terraform -chdir=${{ env.PATH_TO_TFSCRIPT }} init -no-color

      - name: Apply Terraform
        id: terraform_apply
        shell: bash
        run: |
          export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
          export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
          export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
          terramate run --tags dev terraform -chdir=${{ env.PATH_TO_TFSCRIPT }} apply -var 'globalaccount=${{ secrets.GLOBALACCOUNT }}' -var 'build_code_admins=${{ secrets.USERLIST }}' -var 'build_code_developers=${{ secrets.USERLIST }}' -auto-approve -no-color
